import { Coordinate } from "ol/coordinate";
import { LineShape, PolygonShape } from "../Shape/Abstractions";
import { ShapeAssaultArrow } from "../Shape/Arrow/AssaultArrow";
import { ShapeAssaultDirection } from "../Shape/Arrow/AssaultDirection";
import { ShapeAttackArrow } from "../Shape/Arrow/AttachArrow";
import { ShapeCardinalArrow } from "../Shape/Arrow/CardinalArrow";
import { ShapeDoubleArrow } from "../Shape/Arrow/DoubleArrow";
import { ShapeLinetArrow } from "../Shape/Arrow/LineArrow";
import { ShapeLineSearch } from "../Shape/Arrow/LineSearch";
import { ShapeParallSearch } from "../Shape/Arrow/ParallSearch";
import { ShapeSectorSearch } from "../Shape/Arrow/SectorSearch";
import { ShapeSquadCombat } from "../Shape/Arrow/SquadCombat";
import { ShapeStraightArrow } from "../Shape/Arrow/StraightArrow";
import { ShapeTailedAttrackArrow } from "../Shape/Arrow/TailedAttackArrow";
import { ShapeTailedSquadCombat } from "../Shape/Arrow/TailedSquadCombat";
import { ShapeAcrFlag } from "../Shape/Flag/ArcFlag";
import { ShapeRectangleFlag } from "../Shape/Flag/RectangleFlag";
import { ShapeTriangleFlag } from "../Shape/Flag/TriangleFlag";
import { ShapeArc } from "../Shape/Lines/Arc";
import { ShapeBezierSegment } from "../Shape/Lines/BezierSegment";
import { ShapeBezierThreeSegment } from "../Shape/Lines/BezierSegmentThree";
import { ShapeBezierThree } from "../Shape/Lines/BezierThree";
import { ShapeBezier } from "../Shape/Lines/BezierTwo";
import { ShapeCardinal } from "../Shape/Lines/Cardinal";
import { ShapeLine } from "../Shape/Lines/Line";
import { ShapeCircle } from "../Shape/Polygon/Circle";
import { ShapeEllipse } from "../Shape/Polygon/Ellipse";
import { ShapeFreePolygon } from "../Shape/Polygon/FreePolygon";
import { ShapeFreeStar } from "../Shape/Polygon/FreeStar";
import { ShapeGatherPlace } from "../Shape/Polygon/GatherPlace";
import { ShapeLune } from "../Shape/Polygon/Lune";
import { ShapePolygon } from "../Shape/Polygon/Polygon";
import { ShapeRectangle } from "../Shape/Polygon/Rectangle";
import { ShapeRhomboid } from "../Shape/Polygon/Rhomboid";
import { ShapeRhombus } from "../Shape/Polygon/Rhombus";
import { ShapeSector } from "../Shape/Polygon/Sector";
import { ShapeStar } from "../Shape/Polygon/Star";
import { ShapeSurface } from "../Shape/Polygon/Suface";
import { ShaprTrapezoid } from "../Shape/Polygon/Trapezoid";
import { ShapeType } from "./ShapeType";
/** 图形生成器 */
export function ShapeCreator(points: Coordinate[], type: ShapeType, size: number):PolygonShape|LineShape {
    switch (type) {
        case ShapeType.CardinalArrow: return new ShapeCardinalArrow(points);
        case ShapeType.LineArrow: return new ShapeLinetArrow(points);
        case ShapeType.LineSearch: return new ShapeLineSearch(points);
        case ShapeType.ParallSearch: return new ShapeParallSearch(points);
        case ShapeType.SectorSearch: return new ShapeSectorSearch(points);
        case ShapeType.StraightArrow: return new ShapeStraightArrow(points);
        case ShapeType.ArcFlag: return new ShapeAcrFlag(points);
        case ShapeType.Rectangle: return new ShapeRectangleFlag(points);
        case ShapeType.TriangleFlag: return new ShapeTriangleFlag(points);
        case ShapeType.Arc: return new ShapeArc(points);
        case ShapeType.Bezier: return new ShapeBezier(points);
        case ShapeType.BezierSegment: return new ShapeBezierSegment(points);
        case ShapeType.BezierThree: return new ShapeBezierThree(points);
        case ShapeType.BezierSegmentThree: return new ShapeBezierThreeSegment(points);
        case ShapeType.Cardinal: return new ShapeCardinal(points);
        case ShapeType.Line: return new ShapeLine(points);
        case ShapeType.Circle: return new ShapeCircle(points);
        case ShapeType.Ellipse: return new ShapeEllipse(points);
        case ShapeType.FreePolygon: return new ShapeFreePolygon(points);
        case ShapeType.FreeStar: return new ShapeFreeStar(points, { size: size, rid: 0.3 });
        case ShapeType.Polygon: return new ShapePolygon(points, { size });
        case ShapeType.Rhombus: return new ShapeRhombus(points);
        case ShapeType.Sector: return new ShapeSector(points);
        case ShapeType.Star: return new ShapeStar(points, { size });
        case ShapeType.Trapezoid: return new ShaprTrapezoid(points);
        case ShapeType.Rhomboid: return new ShapeRhomboid(points);
        case ShapeType.Surface: return new ShapeSurface(points);
        case ShapeType.Lune: return new ShapeLune(points);
        case ShapeType.Rectangle: return new ShapeRectangle(points);
        case ShapeType.AttachArrow: return new ShapeAttackArrow(points);
        case ShapeType.TailedAttackArrow: return new ShapeTailedAttrackArrow(points);
        case ShapeType.SquadCombat: return new ShapeSquadCombat(points);
        case ShapeType.TailedSquadCombat: return new ShapeTailedSquadCombat(points);
        case ShapeType.AssaultArrow: return new ShapeAssaultArrow(points);
        case ShapeType.AssaultDirection: return new ShapeAssaultDirection(points);
        case ShapeType.DoubleArrow: return new ShapeDoubleArrow(points);
        case ShapeType.GatherPlace: return new ShapeGatherPlace(points);
        default: return new ShapeLine(points);
    }
}