/** 图形类型 */
export enum ShapeType {
    /**圆弧线 */
    Arc = 0,
    /** 二次贝塞尔线条 */
    Bezier = 1,
    /** 二次贝塞尔线段 */
    BezierSegment = 2,
    /** 三次贝塞尔线条 */
    BezierThree = 3,
    /** 三次贝塞尔线段 */
    BezierSegmentThree = 4,
    /** 卡尔迪曲线 */
    Cardinal = 5,
    /** 折线 */
    Line = 6,
    /** 圆 */
    Circle = 100,
    /** 椭圆 */
    Ellipse = 101,
    /** 任意多边形 */
    FreePolygon = 102,
    /** 自由星形 */
    FreeStar = 103,
    /** 集结地 */
    GatherPlace = 104,
    /** 弓形 */
    Lune = 105,
    /** 正多边形 */
    Polygon = 106,
    /** 矩形 */
    Rectangle = 107,
    /** 平行四边形 */
    Rhomboid = 108,
    /** 扇形 */
    Sector = 109,
    /** 正星形 */
    Star = 110,
    /** 等腰梯形 */
    Trapezoid = 111,
    /** 菱形 */
    Rhombus = 112,
    /** 曲面 */
    Surface = 113,
    /**曲线旗帜 */
    ArcFlag = 200,
    /** 矩形旗帜 */
    RectangleFlag = 201,
    /** 三角旗帜 */
    TriangleFlag = 202,
    /** 突击箭头 */
    AssaultArrow = 301,
    /** 突击方法 */
    AssaultDirection = 302,
    /** 进攻箭头 */
    AttachArrow = 303,
    /** 燕尾进攻箭头 */
    TailedAttackArrow = 304,
    /** 作战箭头 */
    SquadCombat = 305,
    /** 燕尾作战箭头 */
    TailedSquadCombat = 306,
    /** 钳击 */
    DoubleArrow = 307,
    /**卡尔迪箭头 */
    CardinalArrow = 308,
    /** 折线箭头 */
    LineArrow = 309,
    /** 折线搜索区 */
    LineSearch = 310,
    /** 平行搜索区 */
    ParallSearch = 311,
    /** 扇形搜索区 */
    SectorSearch = 312,
    /** 直线箭头 */
    StraightArrow = 313,
    
}